#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
cd aurellion
echo debugging the pre-commit hook 1>&2
exit 1
# npm run format && git add -A .

#!/usr/bin/env sh

# . "$(dirname -- "$0")/_/husky.sh"

# npm test